scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 20
    window: 1

- name: interpolation
  type: InterpolationFilter

- name: range
  type: LaserScanRangeFilter
  params:
    lower_threshold: 0.02
    upper_threshold: 4.0