// Generated by gencpp from file jaguar4x4/MotorData.msg
// DO NOT EDIT!


#ifndef JAGUAR4X4_MESSAGE_MOTORDATA_H
#define JAGUAR4X4_MESSAGE_MOTORDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace jaguar4x4
{
template <class ContainerAllocator>
struct MotorData_
{
  typedef MotorData_<ContainerAllocator> Type;

  MotorData_()
    : header()
    , motorPower(0)
    , encoderPos(0)
    , encoderVel(0)
    , encoderDiff(0)
    , motorTemp(0.0)
    , motorCurrent(0.0)  {
    }
  MotorData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motorPower(0)
    , encoderPos(0)
    , encoderVel(0)
    , encoderDiff(0)
    , motorTemp(0.0)
    , motorCurrent(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _motorPower_type;
  _motorPower_type motorPower;

   typedef int64_t _encoderPos_type;
  _encoderPos_type encoderPos;

   typedef int64_t _encoderVel_type;
  _encoderVel_type encoderVel;

   typedef int64_t _encoderDiff_type;
  _encoderDiff_type encoderDiff;

   typedef float _motorTemp_type;
  _motorTemp_type motorTemp;

   typedef float _motorCurrent_type;
  _motorCurrent_type motorCurrent;




  typedef boost::shared_ptr< ::jaguar4x4::MotorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jaguar4x4::MotorData_<ContainerAllocator> const> ConstPtr;

}; // struct MotorData_

typedef ::jaguar4x4::MotorData_<std::allocator<void> > MotorData;

typedef boost::shared_ptr< ::jaguar4x4::MotorData > MotorDataPtr;
typedef boost::shared_ptr< ::jaguar4x4::MotorData const> MotorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jaguar4x4::MotorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jaguar4x4::MotorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jaguar4x4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'jaguar4x4': ['/home/iordanis/Roula/src/motor_and_sensor_controllers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jaguar4x4::MotorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaguar4x4::MotorData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaguar4x4::MotorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaguar4x4::MotorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaguar4x4::MotorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaguar4x4::MotorData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jaguar4x4::MotorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5232fe1210c26e268a1e76fffa8d3933";
  }

  static const char* value(const ::jaguar4x4::MotorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5232fe1210c26e26ULL;
  static const uint64_t static_value2 = 0x8a1e76fffa8d3933ULL;
};

template<class ContainerAllocator>
struct DataType< ::jaguar4x4::MotorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jaguar4x4/MotorData";
  }

  static const char* value(const ::jaguar4x4::MotorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jaguar4x4::MotorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#motor sensor data message from Dr Robot \n\
Header header 	   #timestamp in the header is the time the driver\n\
int64 motorPower	   # motor driver power from motor driver board\n\
int64 encoderPos	   #encoder position reading\n\
int64 encoderVel	   #encoder velocity reading\n\
int64 encoderDiff	   #encoder position differnece reading referee last reading\n\
float32 motorTemp   #motor temperature reading\n\
float32 motorCurrent	  #motor current feedback reading\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::jaguar4x4::MotorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jaguar4x4::MotorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motorPower);
      stream.next(m.encoderPos);
      stream.next(m.encoderVel);
      stream.next(m.encoderDiff);
      stream.next(m.motorTemp);
      stream.next(m.motorCurrent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jaguar4x4::MotorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jaguar4x4::MotorData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motorPower: ";
    Printer<int64_t>::stream(s, indent + "  ", v.motorPower);
    s << indent << "encoderPos: ";
    Printer<int64_t>::stream(s, indent + "  ", v.encoderPos);
    s << indent << "encoderVel: ";
    Printer<int64_t>::stream(s, indent + "  ", v.encoderVel);
    s << indent << "encoderDiff: ";
    Printer<int64_t>::stream(s, indent + "  ", v.encoderDiff);
    s << indent << "motorTemp: ";
    Printer<float>::stream(s, indent + "  ", v.motorTemp);
    s << indent << "motorCurrent: ";
    Printer<float>::stream(s, indent + "  ", v.motorCurrent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JAGUAR4X4_MESSAGE_MOTORDATA_H
