(cl:in-package jaguar4x4-msg)
(cl:export '(HEADER-VAL
          HEADER
          SEQ-VAL
          SEQ
          YAW-VAL
          YAW
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          GYRO_X-VAL
          GYRO_X
          GYRO_Y-VAL
          GYRO_Y
          GYRO_Z-VAL
          GYRO_Z
          ACCEL_X-VAL
          ACCEL_X
          ACCEL_Y-VAL
          ACCEL_Y
          ACCEL_Z-VAL
          ACCEL_Z
          COMP_X-VAL
          COMP_X
          COMP_Y-VAL
          COMP_Y
          COMP_Z-VAL
          COMP_Z
))