controller_frequency: 20.0
recovery_behaviour_enabled: true

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 2.0
  acc_lim_y: 0
  acc_lim_th: 3.0

  max_vel_x: 0.3
  min_vel_x: -0.1
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_trans_vel: 0.3
  min_trans_vel: 0.1
  max_rot_vel: 0.15
  min_rot_vel: -0.15

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false