local_costmap:
   global_frame: /map # Indicates the frame for the costmap to operate in.
   update_frequency: 20.0 # The frequency (in Hz) for map update.
   publish_frequency: 5.0
   width: 2.0 # Width of the map, in meters.
   height: 2.0 # Height of the map, in meters.
   resolution: 0.05 # Resolution of the map in meters per cell.
   static_map: false # Indicates whether the system uses or not a static map.
   rolling_window: true # Use a rolling window map.